---
- name: Validate SSH credentials via jump host
  hosts: localhost
  gather_facts: false

  vars:
    jump_host: "sshjump@ssh.cyberrange.rit.edu"

    targets:
    # Blue Team Boxes
      - name: svc-samba-01
        ip: 100.65.3.17
      - name: svc-database-01
        ip: 100.65.4.179
      - name: svc-redis-01
        ip: 100.65.2.100
      - name: svc-amazin-01
        ip: 100.65.6.229
      - name: svc-ftp-01
        ip: 100.65.8.4
      - name: blue-ubnt-01
        ip: 100.65.3.192
      - name: blue-ubnt-02
        ip: 100.65.2.156
      - name: blue-ubnt-03
        ip: 100.65.7.34
      - name: blue-ubnt-04
        ip: 100.65.8.205
      - name: blue-win-01
        ip: 100.65.3.180
      - name: blue-win-02
        ip: 100.65.8.205
      - name: blue-win-03
        ip: 100.65.6.241
      - name: blue-win-04
        ip: 100.65.6.35
      - name: blue-win-05
        ip: 100.65.2.74
      - name: blue-win-06
        ip: 100.65.8.192
      - name: blue-win-07
        ip: 100.65.8.207
      - name: blue-win-08
        ip: 100.65.3.35
      
      # Red Team Boxes
      - name: red-kali-1
        ip: 100.65.2.138
      - name: red-kali-2
        ip: 100.65.8.111
      - name: red-kali-3
        ip: 100.65.8.11
      - name: red-kali-4
        ip: 100.65.7.169
      - name: red-kali-5
        ip: 100.65.7.92
      - name: red-kali-6
        ip: 100.65.8.20
      - name: red-kali-7
        ip: 100.65.4.219
      - name: red-kali-8
        ip: 100.65.8.177
      - name: red-kali-9
        ip: 100.65.7.16
      - name: red-kali-10
        ip: 100.65.8.202
      - name: red-kali-11
        ip: 100.65.2.232
      - name: red-kali-12
        ip: 100.65.2.114
      - name: red-ubuntu-1
        ip: 100.65.7.179
      - name: red-ubuntu-2
        ip: 100.65.2.63
      - name: red-ubuntu-3
        ip: 100.65.6.175
      - name: red-ubuntu-4
        ip: 100.65.4.182

      

    credentials:
    - { username: "jbezos@cdt.local", password: "AmazonRocks!" }
      #- { username: "jezbos", password: "AmazonRocks!" }
      #- { username: "readuserl1", password: "Day0Fun2026!" }
      #- { username: "readuserl2", password: "Day0Fun2026!" }
      #- { username: "readuserw1", password: "Day0Fun2026!" }
      #- { username: "readuserw2", password: "Day0Fun2026!" }

    report_file: "./ssh_audit_report.txt"

  tasks:

    - name: Initialize report
      ansible.builtin.copy:
        dest: "{{ report_file }}"
        content: "SSH Audit Report\n====================\n\n"

    - name: Test all credential combinations
      ansible.builtin.include_tasks: test_ssh.yml
      loop: "{{ targets | product(credentials) | list }}"
      loop_control:
        label: "{{ item.0.name }} - {{ item.1.username }}"